email_delivery:
      delivery_method: :smtp
      smtp_settings:
        enable_starttls_auto: true
        address: "smtp.gmail.com"
        port: 587
        domain: "smtp.gmail.com" # 'your.domain.com' for GoogleApps
        authentication: :plain
        user_name: "maalejmedti@gmail.com"
        password: "#includesfax123Powerg"
      
 
 email_delivery:
      delivery_method: :sendmail

